[package]
name = "egui-pixelmap-template"
version = "0.0.1"
edition = "2024"

[dependencies]
eframe = "0.32"
env_logger = "0.11"
strum = "0.27"
rand = "0.9"
rand-wyrand = "0.3"
strum_macros = "0.26.4"
